# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-20 21:15
from __future__ import unicode_literals

from django.db import migrations
import wagtail.wagtailcore.blocks
import wagtail.wagtailcore.fields
import wagtail.wagtailembeds.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_homepage_header'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='body',
            field=wagtail.wagtailcore.fields.StreamField([('paragraph', wagtail.wagtailcore.blocks.RichTextBlock()), ('video', wagtail.wagtailembeds.blocks.EmbedBlock())], blank=True),
        ),
    ]
