# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-22 18:38
from __future__ import unicode_literals

from django.db import migrations
import wagtail.wagtailcore.blocks
import wagtail.wagtailcore.fields
import wagtail.wagtailembeds.blocks
import wagtail.wagtailimages.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_auto_20160722_1833'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blankpage',
            name='body',
            field=wagtail.wagtailcore.fields.StreamField([('paragraph', wagtail.wagtailcore.blocks.RichTextBlock()), ('image', wagtail.wagtailimages.blocks.ImageChooserBlock(classname='wagtail-image')), ('video', wagtail.wagtailembeds.blocks.EmbedBlock())], blank=True),
        ),
        migrations.AlterField(
            model_name='thinblankpage',
            name='body',
            field=wagtail.wagtailcore.fields.StreamField([('paragraph', wagtail.wagtailcore.blocks.RichTextBlock()), ('image', wagtail.wagtailimages.blocks.ImageChooserBlock(classname='wagtail-image')), ('video', wagtail.wagtailembeds.blocks.EmbedBlock())], blank=True),
        ),
    ]
