# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-22 18:41
from __future__ import unicode_literals

from django.db import migrations
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_auto_20160722_1838'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blankpage',
            name='body',
            field=wagtail.wagtailcore.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='thinblankpage',
            name='body',
            field=wagtail.wagtailcore.fields.RichTextField(),
        ),
    ]
