# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-19 06:43
from __future__ import unicode_literals

from django.db import migrations
import wagtail.wagtailcore.blocks
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailforms', '0003_capitalizeverbose'),
        ('wagtailcore', '0028_merge'),
        ('wagtailredirects', '0005_capitalizeverbose'),
        ('home', '0014_auto_20160807_1726'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='peoplepageindex',
            name='page_ptr',
        ),
        migrations.AlterField(
            model_name='blankpage',
            name='body',
            field=wagtail.wagtailcore.fields.StreamField([(b'paragraph', wagtail.wagtailcore.blocks.RichTextBlock()), (b'calendar', wagtail.wagtailcore.blocks.StructBlock([(b'url', wagtail.wagtailcore.blocks.CharBlock(required=True))])), (b'mailchimp', wagtail.wagtailcore.blocks.StructBlock([(b'action_url', wagtail.wagtailcore.blocks.CharBlock(required=True)), (b'hidden_field_name', wagtail.wagtailcore.blocks.CharBlock(required=True))]))]),
        ),
        migrations.AlterField(
            model_name='thinblankpage',
            name='body',
            field=wagtail.wagtailcore.fields.StreamField([(b'paragraph', wagtail.wagtailcore.blocks.RichTextBlock()), (b'calendar', wagtail.wagtailcore.blocks.StructBlock([(b'url', wagtail.wagtailcore.blocks.CharBlock(required=True))])), (b'mailchimp', wagtail.wagtailcore.blocks.StructBlock([(b'action_url', wagtail.wagtailcore.blocks.CharBlock(required=True)), (b'hidden_field_name', wagtail.wagtailcore.blocks.CharBlock(required=True))]))]),
        ),
        migrations.DeleteModel(
            name='PeoplePageIndex',
        ),
    ]
